(function(){
  const routes=[
    {keys:['ransom','ransomware'],title:'Ransomware',answer:'Parti dal Playbook e poi usa Analisi per creare una scheda CTI con evidenze, impatto, confidence e decisioni.',links:[['Playbook','playbooks.html'],['Analisi','analyze.html'],['Intelligence','intelligence.html']]},
    {keys:['phishing','email','bec'],title:'Phishing o BEC',answer:'Apri Playbook per orientare il triage, poi usa Analisi per classificare indicatori, tecniche e raccomandazioni.',links:[['Playbook','playbooks.html'],['Analisi','analyze.html']]},
    {keys:['cloud','account','mfa'],title:'Account cloud',answer:'Usa Playbook per impostare le domande di triage e Sicurezza per verificare i controlli presenti.',links:[['Playbook','playbooks.html'],['Sicurezza','security.html'],['Analisi','analyze.html']]},
    {keys:['cve','kev','vulnerabil'],title:'CVE o vulnerabilità',answer:'Apri Intelligence per consultare fonti come CISA KEV, EPSS e NVD. Poi inserisci la CVE in Analisi per il report.',links:[['Intelligence','intelligence.html'],['Analisi','analyze.html']]},
    {keys:['stud','training','manuale','cti'],title:'Studiare CTI',answer:'Segui il percorso Training in ordine: Fondamenti, Fonti, Framework, SOC/IR, Governance e Casi pratici.',links:[['Training','training.html'],['Fondamenti','training-fondamenti.html'],['Fonti','training-fonti.html']]},
    {keys:['fonte','osint','ioc','arricch','enrichment'],title:'Fonti e arricchimento',answer:'Vai su Intelligence per scegliere le fonti aperte. L’arricchimento IOC va fatto solo manualmente e con consenso.',links:[['Intelligence','intelligence.html'],['Analisi','analyze.html']]},
    {keys:['report','ciso','direzione'],title:'Report',answer:'Usa Analisi per generare il report e Governance per capire come presentarlo a un decisore.',links:[['Analisi','analyze.html'],['Governance','training-governance.html']]},
    {keys:['sicurezza','postura','controlli'],title:'Sicurezza',answer:'Apri la checklist Sicurezza per stimare la postura difensiva e individuare le aree da rafforzare.',links:[['Sicurezza','security.html']]}
  ];
  const esc=s=>String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const linkList=a=>a.map(x=>`<a class="pill" href="${x[1]}">${esc(x[0])}</a>`).join(' ');
  function answer(q){const t=q.toLowerCase();const r=routes.find(x=>x.keys.some(k=>t.includes(k)));if(!r)return`Posso orientarti tra Training, Intelligence, Analisi, Sicurezza e Playbook.<p>${linkList([['Training','training.html'],['Intelligence','intelligence.html'],['Analisi','analyze.html'],['Playbook','playbooks.html']])}</p>`;return`<b>${esc(r.title)}</b><br>${esc(r.answer)}<p>${linkList(r.links)}</p>`;}
  function add(role,html){const log=document.getElementById('botMessages');if(!log)return;const d=document.createElement('div');d.className='bot-msg '+role;d.innerHTML=html;log.appendChild(d);log.scrollTop=log.scrollHeight;}
  function init(){if(document.getElementById('siteBot'))return;const box=document.createElement('aside');box.id='siteBot';box.className='site-bot';box.innerHTML=`<button id="botToggle" class="btn primary" type="button">Assistente CTI</button><section id="botPanel" class="card hidden"><h2>Assistente CTI</h2><div id="botMessages" class="bot-messages"></div><div class="actions"><input id="botInput" class="search" autocomplete="off" placeholder="Es. ransomware, CVE, report..."><button id="botSend" class="btn primary" type="button">Invia</button></div><p class="muted">Locale: non invia messaggi a servizi esterni.</p></section>`;document.body.appendChild(box);const panel=document.getElementById('botPanel'),input=document.getElementById('botInput');document.getElementById('botToggle').onclick=()=>{panel.classList.toggle('hidden');if(!panel.classList.contains('hidden')&&!document.querySelector('.bot-msg'))add('assistant','Ciao, dimmi cosa devi fare: studiare CTI, analizzare un incidente, scegliere fonti, creare un report o verificare la sicurezza.');};document.getElementById('botSend').onclick=()=>{const q=input.value.trim();if(!q)return;add('user',esc(q));input.value='';setTimeout(()=>add('assistant',answer(q)),80);};input.onkeydown=e=>{if(e.key==='Enter')document.getElementById('botSend').click();};}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
