(function(){
  const routes=[
    {keys:['ransom','ransomware'],title:'Ransomware',answer:'Ti conviene partire dal Playbook e poi usare Analisi per creare una scheda CTI con evidenze, impatto, confidence e decisioni.',links:[['Playbook','playbooks.html'],['Analisi','analyze.html'],['Intelligence','intelligence.html']]},
    {keys:['phishing','email','bec'],title:'Phishing o BEC',answer:'Apri Playbook per orientare il triage, poi usa Analisi per classificare indicatori, tecniche e raccomandazioni.',links:[['Playbook','playbooks.html'],['Analisi','analyze.html']]},
    {keys:['cloud','account','mfa'],title:'Account cloud',answer:'Usa Playbook per impostare le domande di triage e Sicurezza per verificare i controlli presenti.',links:[['Playbook','playbooks.html'],['Sicurezza','security.html'],['Analisi','analyze.html']]},
    {keys:['cve','kev','vulnerabil'],title:'CVE o vulnerabilità',answer:'Apri Intelligence per consultare fonti come CISA KEV, EPSS e NVD. Poi inserisci la CVE in Analisi per il report.',links:[['Intelligence','intelligence.html'],['Analisi','analyze.html']]},
    {keys:['stud','training','manuale','cti'],title:'Studiare CTI',answer:'Segui il percorso Training in ordine: Fondamenti, Fonti, Framework, SOC/IR, Governance e Casi pratici.',links:[['Training','training.html'],['Fondamenti','training-fondamenti.html'],['Fonti','training-fonti.html']]},
    {keys:['fonte','osint','ioc','arricch','enrichment'],title:'Fonti e arricchimento',answer:'Vai su Intelligence per scegliere le fonti aperte. L’arricchimento IOC va fatto solo manualmente e con consenso.',links:[['Intelligence','intelligence.html'],['Analisi','analyze.html']]},
    {keys:['report','ciso','direzione'],title:'Report',answer:'Usa Analisi per generare il report e Governance per capire come presentarlo a un decisore.',links:[['Analisi','analyze.html'],['Governance','training-governance.html']]},
    {keys:['sicurezza','postura','controlli'],title:'Sicurezza',answer:'Apri la checklist Sicurezza per stimare la postura difensiva e individuare le aree da rafforzare.',links:[['Sicurezza','security.html']]}
  ];
  function e(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
  function links(a){return a.map(x=>`<a class="pill" href="${x[1]}">${e(x[0])}</a>`).join(' ')}
  function answer(q){const t=q.toLowerCase();const r=routes.find(x=>x.keys.some(k=>t.includes(k)));if(!r)return`Posso aiutarti a scegliere il percorso: Training, Intelligence, Analisi, Sicurezza o Playbook.<p>${links([['Training','training.html'],['Intelligence','intelligence.html'],['Analisi','analyze.html'],['Playbook','playbooks.html']])}</p>`;return`<b>${e(r.title)}</b><br>${e(r.answer)}<p>${links(r.links)}</p>`;}
  function msg(role,html){const log=document.getElementById('chatLog');if(!log)return;const d=document.createElement('div');d.className='chat-msg '+role;d.innerHTML=html;log.appendChild(d);log.scrollTop=log.scrollHeight;}
  function init(){if(document.getElementById('siteAssistant'))return;const d=document.createElement('div');d.id='siteAssistant';d.innerHTML=`<button id="chatToggle" class="chat-toggle" type="button">CTI</button><section id="chatPanel" class="chat-panel hidden"><header><b>Assistente CTI</b><button id="chatClose" class="btn ghost" type="button">×</button></header><div id="chatLog" class="chat-log"></div><form id="chatForm" class="chat-form"><input id="chatInput" autocomplete="off" placeholder="Cosa devi fare?"><button class="btn primary" type="submit">Invia</button></form><p class="muted chat-note">Assistente locale: non invia messaggi a servizi esterni.</p></section>`;document.body.appendChild(d);const p=document.getElementById('chatPanel');document.getElementById('chatToggle').onclick=()=>{p.classList.toggle('hidden');if(!p.classList.contains('hidden')&&!document.querySelector('.chat-msg'))msg('bot','Ciao, posso orientarti tra Training, Intelligence, Analisi, Sicurezza e Playbook.');};document.getElementById('chatClose').onclick=()=>p.classList.add('hidden');document.getElementById('chatForm').onsubmit=x=>{x.preventDefault();const i=document.getElementById('chatInput');const q=i.value.trim();if(!q)return;msg('user',e(q));i.value='';setTimeout(()=>msg('bot',answer(q)),80);};}
  document.addEventListener('DOMContentLoaded',init);
})();
