(function(){
  const sources={
    enisa:{name:'ENISA Threat Landscape 2025',url:'https://www.enisa.europa.eu/publications/enisa-threat-landscape-2025',kind:'trend aggregato'},
    cisa:{name:'CISA Cybersecurity Advisories',url:'https://www.cisa.gov/news-events/cybersecurity-advisories',kind:'advisory ufficiale'},
    certeu:{name:'CERT-EU Security Advisories',url:'https://cert.europa.eu/publications/security-advisories',kind:'advisory ufficiale'},
    kev:{name:'CISA KEV Catalog',url:'https://www.cisa.gov/known-exploited-vulnerabilities-catalog',kind:'vulnerabilità sfruttate'}
  };
  const events=[
    {id:'eu-ransom-1',x:505,y:185,from:[360,170],region:'Europa',country:'Europa',city:'Trend regionale',type:'ransomware',label:'Trend ransomware',target:'Sanità, PA e servizi essenziali',actor:'Non attribuito',confidence:'media',severity:'high',source:'enisa',date:'2025',note:'Trend strategico aggregato: non rappresenta un singolo incidente né una vittima identificata.'},
    {id:'us-bec-1',x:215,y:205,from:[510,180],region:'Nord America',country:'Nord America',city:'Trend regionale',type:'phishing',label:'Phishing / BEC',target:'Finanza e imprese',actor:'Non attribuito',confidence:'media',severity:'medium',source:'enisa',date:'2025',note:'Trend strategico aggregato su furto credenziali e frodi email. Non è un attacco live.'},
    {id:'asia-exploit-1',x:735,y:235,from:[505,185],region:'Asia-Pacifico',country:'Asia-Pacifico',city:'Contesto vulnerabilità',type:'exploitation',label:'Sfruttamento vulnerabilità',target:'Servizi esposti e tecnologia',actor:'Solo se citato dall’advisory',confidence:'media',severity:'high',source:'kev',date:'catalogo aggiornabile',note:'Contesto basato su vulnerabilità note come sfruttate. Non geolocalizza una vittima né attribuisce un autore.'},
    {id:'eu-advisory-1',x:470,y:160,from:[250,208],region:'Europa',country:'Unione europea',city:'Advisory',type:'phishing',label:'Campagne email',target:'Organizzazioni UE',actor:'Solo se dichiarato dalla fonte',confidence:'media',severity:'medium',source:'certeu',date:'advisory aggiornabili',note:'Riferimento ad advisory pubblici. Aprire la fonte per verificare data, campagna e ambito effettivo.'},
    {id:'global-kev-1',x:680,y:275,from:[510,180],region:'Globale',country:'Globale',city:'Catalogo KEV',type:'exploitation',label:'KEV / exploit in uso',target:'Prodotti vulnerabili esposti',actor:'Non attribuito',confidence:'alta',severity:'high',source:'kev',date:'catalogo aggiornabile',note:'Il catalogo KEV indica sfruttamento noto, non quale Paese sia attaccato né da chi.'},
    {id:'global-ddos-1',x:330,y:360,from:[505,185],region:'Globale',country:'Globale',city:'Trend regionale',type:'ddos',label:'DDoS / hacktivism',target:'Servizi digitali e PA',actor:'Non attribuito',confidence:'bassa',severity:'medium',source:'enisa',date:'2025',note:'Trend aggregato: richiede validazione locale con telemetria WAF/CDN e log di rete.'},
    {id:'cisa-advisory-1',x:820,y:390,from:[690,250],region:'Globale',country:'Stati Uniti / globale',city:'Advisory',type:'malware',label:'Malware e intrusioni',target:'Infrastrutture e organizzazioni',actor:'Solo se dichiarato dalla fonte',confidence:'media',severity:'medium',source:'cisa',date:'advisory aggiornabili',note:'Aprire l’advisory ufficiale per verificare campagna, attore, prodotti coinvolti e data.'}
  ];
  function sevClass(s){return s==='high'?'high':s==='medium'?'medium':'low'}
  function activeEvents(){const f=document.querySelector('.map-filter.active')?.dataset.mapFilter||'all';return f==='all'?events:events.filter(e=>e.type===f)}
  function arcPath(a,b){const mx=(a[0]+b[0])/2,my=Math.min(a[1],b[1])-80;return`M${a[0]},${a[1]} Q${mx},${my} ${b[0]},${b[1]}`}
  function renderMap(){const spots=$('attackHotspots'),links=$('attackLinks'),stats=$('attackMapStats');if(!spots||!links)return;const ev=activeEvents();links.innerHTML=ev.map(e=>`<path class="attack-arc ${e.type}" d="${arcPath(e.from,[e.x,e.y])}"/>`).join('');spots.innerHTML=ev.map(e=>`<g class="hotspot ${e.type} ${sevClass(e.severity)}" data-attack="${e.id}" tabindex="0" role="button" aria-label="${esc(e.label)} ${esc(e.country)}"><circle class="pulse" cx="${e.x}" cy="${e.y}" r="18"></circle><circle class="core" cx="${e.x}" cy="${e.y}" r="7"></circle></g>`).join('');document.querySelectorAll('[data-attack]').forEach(n=>{n.onclick=()=>selectAttack(n.dataset.attack);n.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectAttack(n.dataset.attack)}}});if(stats){const bySource={};events.forEach(e=>{const s=sources[e.source].name;bySource[s]=(bySource[s]||0)+1});stats.innerHTML=Object.entries(bySource).map(([k,v])=>`<article class="metric mini"><small>${esc(k)}</small><b>${v}</b><span class="muted">punti di contesto</span></article>`).join('')}}
  function selectAttack(id){const e=events.find(x=>x.id===id),box=$('attackDetails');if(!e||!box)return;const s=sources[e.source];box.innerHTML=`<h3>${esc(e.label)}</h3><span class="pill risk-${sevClass(e.severity)}">Rischio ${esc(e.severity)}</span><p><b>Area:</b> ${esc(e.city)}, ${esc(e.country)} · ${esc(e.region)}</p><p><b>Bersaglio:</b> ${esc(e.target)}</p><p><b>Attore:</b> ${esc(e.actor)}</p><p><b>Confidence:</b> ${esc(e.confidence)}</p><p><b>Fonte:</b> <a class="pill" target="_blank" rel="noreferrer" href="${esc(s.url)}">${esc(s.name)}</a><br><span class="muted">${esc(s.kind)} · riferimento: ${esc(e.date)}</span></p><p><b>Motivazione CTI:</b> ${esc(e.note)}</p><p class="privacy"><b>Limite:</b> questo punto è contesto con fonte, non prova di un attacco live contro una vittima specifica. L’attribuzione è riportata solo quando dichiarata dalla fonte.</p>`;localStorage.setItem('attack-profiler-selected-map-event',JSON.stringify({...e,source_name:s.name,source_url:s.url,source_kind:s.kind}));}
  function initFilters(){document.querySelectorAll('.map-filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.map-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderMap();});}
  const oldRender=render;render=function(d){oldRender(d);const selected=JSON.parse(localStorage.getItem('attack-profiler-selected-map-event')||'null');if(selected){d.global_attack_map_context={selected_event:selected,events_count:events.length,disclaimer:'Mappa di contesto con fonti; non attribuzione certa.'};$('report').textContent=$('report').textContent+`\n\nMappa globale attacchi\n- Contesto: ${selected.label} · ${selected.country} · ${selected.target}\n- Fonte: ${selected.source_name||selected.source} · ${selected.source_url||'-'}\n- Tipo fonte: ${selected.source_kind||'-'}\n- Riferimento: ${selected.date}\n- Attore: ${selected.actor}\n- Limite: contesto con fonte, non prova certa.`;}};
  document.addEventListener('DOMContentLoaded',()=>{initFilters();renderMap();selectAttack(events[0].id);});initFilters();renderMap();
})();
