(function(){
  const events=[
    {id:'eu-ransom-1',x:505,y:185,from:[360,170],region:'Europa',country:'Germania',city:'Francoforte',type:'ransomware',label:'Ransomware',target:'Sanità / PA locale',actor:'Ransomware ecosystem',confidence:'media',severity:'high',note:'Pattern coerente con campagne estorsive contro servizi essenziali. Validare con log, note di riscatto, EDR e backup.'},
    {id:'us-bec-1',x:215,y:205,from:[510,180],region:'Nord America',country:'Stati Uniti',city:'Costa Est',type:'phishing',label:'Phishing / BEC',target:'Finanza e imprese',actor:'Cybercrime finanziario',confidence:'media',severity:'medium',note:'Frodi email e furto credenziali: verificare header, regole mailbox, accessi anomali e MFA.'},
    {id:'asia-exploit-1',x:735,y:235,from:[505,185],region:'Asia-Pacifico',country:'Giappone',city:'Tokyo',type:'exploitation',label:'Exploitation',target:'Tecnologia / servizi esposti',actor:'APT o cybercrime da validare',confidence:'bassa',severity:'high',note:'Scenario legato a vulnerabilità esposte: correlare con KEV, NVD, patch level e scansioni autorizzate interne.'},
    {id:'uk-phish-1',x:470,y:160,from:[250,208],region:'Europa',country:'Regno Unito',city:'Londra',type:'phishing',label:'Campagna phishing',target:'Finanza',actor:'Cluster email/script',confidence:'media',severity:'medium',note:'Campagna a larga scala: cercare URL, domini nuovi, allegati, click e autenticazioni sospette.'},
    {id:'india-exploit-1',x:680,y:275,from:[510,180],region:'Asia',country:'India',city:'Bengaluru',type:'exploitation',label:'Exploit activity',target:'Education / servizi web',actor:'Non attribuito',confidence:'bassa',severity:'low',note:'Attività generica di exploitation: utile come contesto, non come indicatore di compromissione locale.'},
    {id:'br-ddos-1',x:330,y:360,from:[505,185],region:'Sud America',country:'Brasile',city:'San Paolo',type:'ddos',label:'DDoS',target:'Provider e servizi digitali',actor:'Hacktivism / botnet',confidence:'bassa',severity:'medium',note:'DDoS spesso legato a botnet o tensioni geopolitiche: verificare volumi, ASN, WAF/CDN e impatto servizio.'},
    {id:'au-mal-1',x:820,y:390,from:[690,250],region:'Oceania',country:'Australia',city:'Sydney',type:'malware',label:'Malware',target:'PMI e servizi',actor:'Cybercrime opportunistico',confidence:'bassa',severity:'medium',note:'Indicazione di scenario: correlare con EDR, hash, email gateway e telemetria DNS/proxy.'},
    {id:'za-ransom-1',x:515,y:405,from:[505,185],region:'Africa',country:'Sud Africa',city:'Johannesburg',type:'ransomware',label:'Ransomware',target:'Servizi e manifattura',actor:'Ransomware ecosystem',confidence:'media',severity:'high',note:'Contesto ransomware: validare lateral movement, backup, credenziali e possibili esfiltrazioni.'}
  ];
  const typeColor={ransomware:'#fb7185',phishing:'#f59e0b',exploitation:'#a78bfa',ddos:'#22c55e',malware:'#38bdf8'};
  function sevClass(s){return s==='high'?'high':s==='medium'?'medium':'low'}
  function activeEvents(){const f=document.querySelector('.map-filter.active')?.dataset.mapFilter||'all';return f==='all'?events:events.filter(e=>e.type===f)}
  function arcPath(a,b){const mx=(a[0]+b[0])/2,my=Math.min(a[1],b[1])-80;return`M${a[0]},${a[1]} Q${mx},${my} ${b[0]},${b[1]}`}
  function renderMap(){const spots=$('attackHotspots'),links=$('attackLinks'),stats=$('attackMapStats');if(!spots||!links)return;const ev=activeEvents();links.innerHTML=ev.map(e=>`<path class="attack-arc ${e.type}" d="${arcPath(e.from,[e.x,e.y])}"/>`).join('');spots.innerHTML=ev.map(e=>`<g class="hotspot ${e.type} ${sevClass(e.severity)}" data-attack="${e.id}" tabindex="0" role="button" aria-label="${esc(e.label)} ${esc(e.country)}"><circle class="pulse" cx="${e.x}" cy="${e.y}" r="18"></circle><circle class="core" cx="${e.x}" cy="${e.y}" r="7"></circle></g>`).join('');document.querySelectorAll('[data-attack]').forEach(n=>{n.onclick=()=>selectAttack(n.dataset.attack);n.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();selectAttack(n.dataset.attack)}}});if(stats){const byRegion={};events.forEach(e=>byRegion[e.region]=(byRegion[e.region]||0)+1);stats.innerHTML=Object.entries(byRegion).map(([k,v])=>`<article class="metric mini"><small>${esc(k)}</small><b>${v}</b><span class="muted">eventi campione</span></article>`).join('')}}
  function selectAttack(id){const e=events.find(x=>x.id===id);const box=$('attackDetails');if(!e||!box)return;box.innerHTML=`<h3>${esc(e.label)}</h3><span class="pill risk-${sevClass(e.severity)}">Rischio ${esc(e.severity)}</span><p><b>Area:</b> ${esc(e.city)}, ${esc(e.country)} · ${esc(e.region)}</p><p><b>Bersaglio:</b> ${esc(e.target)}</p><p><b>Attore ipotizzato:</b> ${esc(e.actor)}</p><p><b>Confidence:</b> ${esc(e.confidence)}</p><p><b>Motivazione CTI:</b> ${esc(e.note)}</p><p class="privacy"><b>Limite:</b> mappa di contesto, non attribuzione certa né prova di attacco in tempo reale.</p>`;localStorage.setItem('attack-profiler-selected-map-event',JSON.stringify(e));}
  function initFilters(){document.querySelectorAll('.map-filter').forEach(b=>b.onclick=()=>{document.querySelectorAll('.map-filter').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderMap();});}
  const oldRender=render;
  render=function(d){oldRender(d);const selected=JSON.parse(localStorage.getItem('attack-profiler-selected-map-event')||'null');if(selected){d.global_attack_map_context={selected_event:selected,events_count:events.length,disclaimer:'Mappa di contesto CTI, non attribuzione certa.'};$('report').textContent=$('report').textContent+`\n\nMappa globale attacchi\n- Evento selezionato: ${selected.label} · ${selected.country} · ${selected.target}\n- Attore ipotizzato: ${selected.actor}\n- Confidence: ${selected.confidence}\n- Nota: ${selected.note}\n- Limite: mappa di contesto, non prova certa.`;}}
  document.addEventListener('DOMContentLoaded',()=>{initFilters();renderMap();selectAttack(events[0].id);});
  initFilters();renderMap();
})();
