(function(){
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const routes=[
    {keys:['ransom','cifr','backup','riscatto'],title:'Scenario ransomware',steps:['Apri Analisi e incolla descrizione/log essenziali.','Vai su Playbook → Ransomware.','Preserva EDR, AD, VPN, file server, backup e proxy.','Verifica esfiltrazione prima di parlare solo di cifratura.','Usa Intelligence per contesto Ransomfeed/KEV.'],links:[['Analisi','analyze.html'],['Playbook','playbooks.html'],['Intelligence','intelligence.html']]},
    {keys:['phish','email','bec','credenzial','mfa','mailbox'],title:'Scenario phishing/BEC',steps:['Carica header o estratto email in Analisi.','Controlla login IdP, MFA, regole mailbox e forwarding.','Revoca sessioni e token se c’è compromissione account.','Cerca destinatari simili e click correlati.'],links:[['Analisi','analyze.html'],['Playbook phishing','playbooks.html']]},
    {keys:['cloud','oauth','tenant','office','m365','google','account'],title:'Account cloud compromesso',steps:['Raccogli audit IdP/cloud, IP accesso, device, app OAuth.','Verifica impossible travel, download massivi e regole mailbox.','Revoca token/sessioni e rimuovi app sospette.','Valuta data exposure e obblighi privacy.'],links:[['Analisi','analyze.html'],['Sicurezza','security.html']]},
    {keys:['cve','kev','vulnerab','patch','exploit'],title:'Vulnerabilità / KEV',steps:['Cerca CVE in Intelligence e arricchisci da Analisi se configurato.','Verifica asset esposti e criticità business.','Controlla WAF/web/EDR per segni di exploitation.','Applica patch o mitigazione temporanea.'],links:[['Intelligence','intelligence.html'],['Analisi','analyze.html']]},
    {keys:['impar','training','stud','cti','mitre','diamond','pyramid'],title:'Formazione CTI',steps:['Parti da Training → Fondamenti.','Poi passa a Fonti, Framework, SOC/IR e Governance.','Usa i Playbook per collegare teoria e pratica.'],links:[['Training','training.html'],['Fondamenti','training-fondamenti.html'],['Framework','training-framework.html']]},
    {keys:['sicurezza','mfa','backup','edr','siem','controlli'],title:'Verifica sicurezza',steps:['Apri la pagina Sicurezza e compila la checklist.','Priorità: MFA, log, backup immutabili, EDR, patch, segmentazione.','Usa lo score per orientare remediation e report CISO.'],links:[['Sicurezza','security.html']]}
  ];
  function answer(q){const s=q.toLowerCase();const hit=routes.find(r=>r.keys.some(k=>s.includes(k)));return hit||{title:'Guida rapida',steps:['Per analizzare un incidente usa Analisi.','Per capire il contesto usa Intelligence.','Per imparare usa Training.','Per procedure rapide usa Playbook.','Per postura difensiva usa Sicurezza.'],links:[['Analisi','analyze.html'],['Intelligence','intelligence.html'],['Training','training.html'],['Playbook','playbooks.html'],['Sicurezza','security.html']]};}
  function msg(role,html){const m=document.createElement('div');m.className='bot-msg '+role;m.innerHTML=html;return m;}
  function renderAnswer(q){const a=answer(q);return `<b>${esc(a.title)}</b><ol>${a.steps.map(x=>`<li>${esc(x)}</li>`).join('')}</ol><p>${a.links.map(([t,u])=>`<a class="pill" href="${u}">${esc(t)}</a>`).join(' ')}</p><p class="muted">Guida difensiva: non fornisce istruzioni offensive né invia dati fuori dal browser.</p>`;}
  function init(){if(document.getElementById('siteBot'))return;const w=document.createElement('section');w.id='siteBot';w.className='site-bot';w.innerHTML=`<button id="botToggle" class="btn primary" type="button">Assistente</button><div id="botPanel" class="card hidden"><h2>Assistente del sito</h2><p class="muted">Dimmi cosa devi fare: ransomware, phishing, CVE, cloud, training, sicurezza...</p><div id="botMessages" class="bot-messages"></div><div class="actions"><input id="botInput" class="search" placeholder="Es. ho un caso ransomware"><button id="botAsk" class="btn primary" type="button">Chiedi</button></div></div>`;document.body.appendChild(w);const panel=document.getElementById('botPanel'),msgs=document.getElementById('botMessages'),inp=document.getElementById('botInput');document.getElementById('botToggle').onclick=()=>panel.classList.toggle('hidden');function ask(){const q=inp.value.trim();if(!q)return;msgs.appendChild(msg('user',esc(q)));msgs.appendChild(msg('assistant',renderAnswer(q)));inp.value='';msgs.scrollTop=msgs.scrollHeight;}document.getElementById('botAsk').onclick=ask;inp.onkeydown=e=>{if(e.key==='Enter')ask();};msgs.appendChild(msg('assistant',renderAnswer('guida')));}
  document.addEventListener('DOMContentLoaded',init);init();
})();
