(function(){
  const statuses=['da contestualizzare','in monitoraggio','da validare','blocco consigliato','archiviato'];
  if(typeof helps==='object')helps.cti=['Triage CTI','Sezione difensiva per collegare ogni indicatore a fonte, affidabilità, confidence, impatto, stato operativo e motivazione della decisione.'];
  if(Array.isArray(glossary))glossary.splice(2,0,['Triage CTI','Valutazione operativa degli indicatori per decidere monitoraggio, validazione, blocco o archiviazione.'],['Confidence','Solidità stimata del collegamento tra indicatore, contesto e decisione.']);
  const rows=iocs=>Object.entries(iocs||{}).flatMap(([type,values])=>(values||[]).map(value=>({type,value})));
  function hasText(text,value){return String(text||'').toLowerCase().includes(String(value||'').toLowerCase());}
  function src(value,text,mode,local){if(hasText(text,value))return'osservato dall’utente';if(local)return'inferenza locale';if(String(mode||'').includes('backend'))return'backend';return'inferenza locale';}
  function rel(source,type){if(source==='osservato dall’utente')return type==='cve'?'media':'alta';return'media';}
  function conf(type,source,risk){let n={hash:.88,ip:.74,domain:.70,url:.76,email:.66,cve:.72,file:.64}[type]||.60;if(source==='osservato dall’utente')n+=.08;if(source==='backend')n+=.03;if(risk==='high')n+=.04;return Math.min(.95,n);}
  function imp(type,d){const s=d.executive_summary||{},risk=s.risk,t=s.tactics||[];if(type==='hash'||type==='url'||type==='cve')return risk==='high'?'alto':'medio';if(type==='ip'||type==='domain')return t.includes('Command and Control')||t.includes('Exfiltration')?'alto':'medio';if(type==='email'||type==='file')return risk==='low'?'basso':'medio';return risk==='high'?'alto':'medio';}
  function rec(impact,reliability,confidence){const hi=impact==='alto',med=impact==='medio',ok=reliability==='alta'||reliability==='media',strong=confidence>=.78;if(hi&&ok&&strong)return['blocco consigliato','Impatto alto, fonte adeguata e confidence elevata: valutare un blocco proporzionato e documentato.'];if((hi&&ok)||(med&&confidence>=.70))return['da validare','Indicatore rilevante: confermare con log, asset coinvolti e contesto prima di estendere la misura.'];if(med)return['in monitoraggio','Impatto medio: monitorare su SIEM, EDR, DNS o proxy e avviare hunting retrospettivo.'];return['da contestualizzare','Servono più elementi: frequenza, asset coinvolti, owner e baseline.'];}
  function build(d,text,local){const risk=(d.executive_summary||{}).risk||'medium',time=d.generated_at||new Date().toISOString(),old=Array.isArray(d.cti_triage)?d.cti_triage:[];return rows(d.iocs).map(({type,value})=>{const prev=old.find(x=>x.type===type&&x.value===value)||{},source=prev.source||src(value,text,d.mode,local),reliability=prev.reliability||rel(source,type),confidence=Number(prev.confidence)||conf(type,source,risk),impact=prev.impact||imp(type,d),r=rec(impact,reliability,confidence);return{type,value,source,timestamp:time,reliability,confidence,impact,status:prev.status||r[0],recommended_decision:r[0],reason:prev.reason||r[1],privacy_notice:'Arricchimento solo manuale: verificare autorizzazione, necessità, minimizzazione del dato e policy interne prima di usare fonti esterne.'};});}
  const oldNormalize=normalize;
  normalize=function(d,text,local){d=oldNormalize(d,text,local);d.schema_version='1.3';if(!d.sources.some(x=>String(x.name||'').includes('Triage CTI')))d.sources.push({name:'Triage CTI locale',type:'matrice impatto x fiducia',reliability:'media'});d.cti_triage=build(d,text,local);return d;};
  renderTabs=function(){const names=[['summary','Sintesi'],['cti','Triage CTI'],['iocs','IOC/CVE'],['timeline','Kill chain'],['tech','MITRE'],['groups','Gruppi/TTP'],['actions','Azioni'],['sources','Fonti'],['report','Report']];$('tabs').innerHTML=names.map(([id,n],i)=>`<button class="btn ghost tab ${i?'':'active'}" data-tab="${id}">${n}</button>`).join('');document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>showPanel(b.dataset.tab,b));showPanel('summary',document.querySelector('.tab'));};
  const oldRender=render;
  render=function(d){oldRender(d);renderCti(d);$('report').textContent=makeReport(d);};
  function renderCti(d){const data=d.cti_triage||[],box=$('cti');if(!box)return;box.innerHTML=data.length?`<div class="cti-intro"><b>Workflow difensivo:</b> decisione basata su impatto x fiducia. Nessun indicatore viene inviato automaticamente a terzi.</div><div class="cti-grid">${data.map((r,i)=>`<article class="ioc-card item"><div class="ioc-head"><div><small>${esc(r.type.toUpperCase())}</small><h3>${esc(r.value)}</h3></div><span class="pill risk-${r.impact==='alto'?'high':r.impact==='medio'?'medium':'low'}">Impatto ${esc(r.impact)}</span></div><div class="cti-meta"><span>Provenienza: <b>${esc(r.source)}</b></span><span>Timestamp: <b>${esc(new Date(r.timestamp).toLocaleString())}</b></span><span>Affidabilità: <b>${esc(r.reliability)}</b></span><span>Confidence: <b>${pct(r.confidence)}%</b></span></div><label>Stato operativo<select class="cti-status" data-cti="${i}">${statuses.map(o=>`<option ${o===r.status?'selected':''}>${o}</option>`).join('')}</select></label><p><b>Decisione consigliata:</b> ${esc(r.recommended_decision)}</p><p><b>Motivazione:</b> ${esc(r.reason)}</p><p class="privacy"><b>Privacy / OPSEC:</b> ${esc(r.privacy_notice)}</p><button class="btn ghost enrich" data-ioc="${esc(r.value)}" type="button">Arricchisci IOC</button></article>`).join('')}</div>`:'<p>Nessun IOC da triagiare. Inserisci IP, domini, URL, hash, email, CVE o file nella descrizione dell’evento.</p>';document.querySelectorAll('.cti-status').forEach(sel=>sel.onchange=e=>{const i=Number(e.target.dataset.cti);if(lastData&&lastData.cti_triage&&lastData.cti_triage[i]){lastData.cti_triage[i].status=e.target.value;$('report').textContent=makeReport(lastData);}});document.querySelectorAll('#cti .enrich').forEach(b=>b.onclick=()=>enrich(b.dataset.ioc));}
  enrich=function(ioc){if(!$('allowEnrich')?.checked){alert('Enrichment manuale non attivo. Attiva prima il consenso nella sezione IOC/CVE. Nessun dato è stato inviato.');return;}alert(`Enrichment manuale richiesto per: ${ioc||'IOC selezionato'}\n\nQuesta PWA non invia automaticamente indicatori a fonti esterne.`);};
  function ctiReport(d){return(d.cti_triage||[]).map(r=>`- ${r.type}: ${r.value} | provenienza: ${r.source} | timestamp: ${r.timestamp} | affidabilità: ${r.reliability} | confidence: ${pct(r.confidence)}% | impatto: ${r.impact} | stato: ${r.status} | decisione: ${r.recommended_decision} | motivo: ${r.reason}`).join('\n')||'-';}
  const oldMakeReport=makeReport;
  makeReport=function(d){return oldMakeReport(d).replace('\n\nTecniche MITRE',`\n\nTriage CTI\n${ctiReport(d)}\n\nTecniche MITRE`);};
})();
