(function(){
  const ENRICH_API='https://attack-profiler-pwa.onrender.com/api/enrich';
  const sourceMatrix={
    ip:['AbuseIPDB','GreyNoise','RIPEstat','Spamhaus','Cisco Talos','ThreatFox'],
    domain:['crt.sh','VirusTotal manuale','URLhaus','ThreatFox','OTX','Cisco Talos'],
    url:['URLhaus','VirusTotal manuale','ThreatFox','OTX'],
    hash:['MalwareBazaar','VirusTotal manuale','ThreatFox','OTX'],
    cve:['CISA KEV','FIRST EPSS','NVD/NIST','CERT-EU','CISA Advisories'],
    email:['Have I Been Pwned manuale','Mozilla Monitor','log email gateway','IdP audit'],
    file:['MalwareBazaar se hash disponibile','YARA/Sigma interni','EDR telemetry']
  };
  function inferType(v){v=String(v||'').trim();if(/^CVE-\d{4}-\d{4,}$/i.test(v))return'cve';if(/^[a-f0-9]{32,64}$/i.test(v))return'hash';if(/^https?:\/\//i.test(v))return'url';if(/^\d{1,3}(\.\d{1,3}){3}$/.test(v))return'ip';if(/@/.test(v))return'email';if(/\./.test(v))return'domain';return'unknown'}
  function renderFallback(type,value,msg){const sources=sourceMatrix[type]||['CISA KEV','NVD','MITRE ATT&CK','OSINT manuale'];return{ok:false,value,type,timestamp:new Date().toISOString(),mode:'fallback client',error:msg||'Endpoint /api/enrich non disponibile',sources:sources.map(name=>({name,status:'consultazione manuale consigliata'})),summary:'Aggregatore backend non ancora configurato. Il frontend non invia IOC a terzi e suggerisce solo fonti da consultare o integrare lato backend.',recommendation:'Configura il backend Render con allowlist, cache, rate limit e chiavi API lato server.'};}
  function showResult(data){let box=document.getElementById('enrichResult');if(!box){box=document.createElement('section');box.id='enrichResult';box.className='card';const res=document.getElementById('results')||document.querySelector('main');res?.prepend(box);}box.innerHTML=`<h2>Arricchimento CTI</h2><div class="item"><h3>${esc(data.type||'IOC')} · ${esc(data.value||'')}</h3><p><b>Modalità:</b> ${esc(data.mode||'backend')}</p><p><b>Timestamp:</b> ${esc(data.timestamp||new Date().toISOString())}</p><p><b>Sintesi:</b> ${esc(data.summary||'Risultati aggregati da fonti configurate.')}</p><p><b>Raccomandazione:</b> ${esc(data.recommendation||'Validare sempre con log interni e contesto del caso.')}</p>${data.error?`<p class="privacy"><b>Nota:</b> ${esc(data.error)}</p>`:''}</div><div class="global-grid">${(data.sources||[]).map(s=>`<article class="item"><h3>${esc(s.name||s.source||'Fonte')}</h3><p><b>Stato:</b> ${esc(s.status||s.verdict||'n/d')}</p><p>${esc(s.detail||s.note||'Risultato da validare.')}</p></article>`).join('')}</div><p class="privacy"><b>Privacy / OPSEC:</b> arricchimento solo su click esplicito. Non inviare log completi, dati personali o dettagli d’indagine a fonti esterne non autorizzate.</p>`;}
  async function callBackend(type,value){const r=await fetch(ENRICH_API,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({type,value,consent:true,source_policy:'allowlisted_backend_only'})});if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}
  window.enrich=async function(ioc){const value=String(ioc||'').trim();if(!value)return;const allow=document.getElementById('allowEnrich');if(allow&&!allow.checked){alert('Attiva prima il consenso di enrichment manuale. Nessun dato è stato inviato.');return;}const type=inferType(value);showResult({type,value,mode:'in corso',timestamp:new Date().toISOString(),summary:'Interrogo il backend aggregatore CTI...',recommendation:'Attendere risposta.'});try{const data=await callBackend(type,value);showResult({...data,type:data.type||type,value:data.value||value,timestamp:data.timestamp||new Date().toISOString(),mode:data.mode||'backend aggregatore'});}catch(e){showResult(renderFallback(type,value,e.message));}
  };
})();
