(function(){
  const officialLinks=[
    {name:'CISA KEV',url:'https://www.cisa.gov/known-exploited-vulnerabilities-catalog',use:'Vulnerabilità sfruttate realmente.'},
    {name:'NVD/NIST CVE API',url:'https://nvd.nist.gov/developers/vulnerabilities',use:'CVE, CVSS e filtri KEV.'},
    {name:'FIRST EPSS',url:'https://www.first.org/epss/api',use:'Probabilità statistica di sfruttamento.'},
    {name:'CERT-EU',url:'https://cert.europa.eu/publications/security-advisories',use:'Advisory europei.'},
    {name:'ENISA Threat Landscape',url:'https://www.enisa.europa.eu/publications/enisa-threat-landscape-2025',use:'Quadro strategico annuale.'},
    {name:'Ransomfeed',url:'https://ransomfeed.it/',use:'Dashboard OSINT pubblica ransomware.'}
  ];
  const ransomSource={name:'Ransomfeed',url:'https://ransomfeed.it/',kind:'OSINT pubblico ransomware',license:'CC BY 4.0',reliability:'media'};
  const ransomSnapshot={updated_at:'2026-07-05 snapshot da pagina pubblica',stats:{global_7d:192,italy_7d:5,groups_2026:104,countries_2026:123,global_total:26808,global_2026:4641,italy_total:781,italy_2026:143},events:[
    {date:'2026-07-03',country:'USA',victim:'oakparkmi.gov',group:'incransom',time:'00:55'},
    {date:'2026-07-03',country:'Switzerland',victim:'Ferrum AG',group:'anubis',time:'00:51'},
    {date:'2026-07-02',country:'Spain',victim:'holidaypalace.com',group:'apt73/bashe',time:'17:57'},
    {date:'2026-07-02',country:'Vietnam',victim:'ritavo.com',group:'apt73/bashe',time:'17:57'},
    {date:'2026-07-02',country:'Brazil',victim:'tambasa.com',group:'incransom',time:'16:55'},
    {date:'2026-07-02',country:'USA',victim:'tricountyhs.org',group:'incransom',time:'16:54'},
    {date:'2026-07-02',country:'USA',victim:'acworth-ga.gov',group:'incransom',time:'16:32'},
    {date:'2026-07-02',country:'Italy',victim:'flazio.com',group:'apt73/bashe',time:'16:21'},
    {date:'2026-07-02',country:'Brazil',victim:'Service IT',group:'worldleaks',time:'15:54'},
    {date:'2026-07-02',country:'Pakistan',victim:'Treet Group of Companies',group:'worldleaks',time:'15:54'},
    {date:'2026-07-02',country:'Canada',victim:'X-Copper Professional',group:'moneymessage',time:'09:55'},
    {date:'2026-07-02',country:'Australia',victim:'Pennant Hills Golf Club',group:'qilin',time:'09:26'},
    {date:'2026-07-02',country:'Germany',victim:'Tofutown',group:'payload',time:'07:26'},
    {date:'2026-07-01',country:'France',victim:'Mairie Thiverval Grignon',group:'medusalocker',time:'22:30'},
    {date:'2026-07-01',country:'India',victim:'CTM India Limited motherson INDIA',group:'thegentlemen',time:'22:24'}
  ]};
  let globalMoment=null,ransomData=ransomSnapshot;
  function safeDate(d){try{return new Date(d).toLocaleDateString('it-IT')}catch(e){return String(d||'-')}}
  async function getJson(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}
  async function getText(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);return r.text();}
  function staticLandscape(){return{updated_at:new Date().toISOString(),mode:'fallback/strategico',geo:[['Europa','Ransomware, DDoS, campagne contro PA, sanità, trasporti e servizi digitali.'],['Nord America','Ransomware, furto credenziali, compromissione servizi esposti, frodi BEC.'],['Asia-Pacifico','Sfruttamento vulnerabilità, supply chain, furto dati e attività cybercrime/espionage.']],sectors:['PA/Gov','Sanità','Finanza','Energia/OT','Trasporti','Cloud/SaaS','PMI'],actors:['Ransomware ecosystem','Cybercrime finanziario','APT statali o para-statali','Hacktivism geopolitico'],note:'Quadro orientativo: usare solo come contesto, non come attribuzione automatica.'};}
  async function loadKev(){const data=await getJson('https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json');return(data.vulnerabilities||[]).slice(-8).reverse().map(v=>({id:v.cveID,title:v.vulnerabilityName||v.shortDescription||v.cveID,vendor:v.vendorProject||'-',product:v.product||'-',due:v.dueDate||'-',source:'CISA KEV'}));}
  async function loadEpss(){const data=await getJson('https://api.first.org/data/v1/epss?order=!epss&limit=8');return(data.data||[]).map(v=>({id:v.cve,epss:Number(v.epss||0),percentile:Number(v.percentile||0),source:'FIRST EPSS'}));}
  function parseRansomfeedHtml(html){const text=html.replace(/<[^>]+>/g,' ').replace(/\s+/g,' '),stats={};const n=(re)=>{const m=text.match(re);return m?Number(m[1]):null};stats.global_7d=n(/7 giorni globale\s+(\d+)/i);stats.italy_7d=n(/7 giorni Italia\s+(\d+)/i);stats.groups_2026=n(/Gruppi attivi 2026\s+(\d+)/i);stats.countries_2026=n(/Paesi colpiti 2026\s+(\d+)/i);stats.global_total=n(/Globale totale\s+(\d+)/i);stats.global_2026=n(/Globale 2026\s+(\d+)/i);stats.italy_total=n(/Italia totale\s+(\d+)/i);stats.italy_2026=n(/Italia 2026\s+(\d+)/i);const re=/(20\d{2}-\d{2}-\d{2})\s+([A-Za-z][A-Za-z .-]+?)\s+(.+?)\s+(incransom|anubis|apt73\/bashe|worldleaks|moneymessage|qilin|payload|spacebears|medusalocker|thegentlemen)\s+(\d{2}:\d{2})/gi;const events=[];let m;while((m=re.exec(text))&&events.length<18){events.push({date:m[1],country:m[2].trim(),victim:m[3].trim().slice(0,80),group:m[4],time:m[5]});}return{updated_at:new Date().toISOString(),stats:{...ransomSnapshot.stats,...Object.fromEntries(Object.entries(stats).filter(([,v])=>v!==null))},events:events.length?events:ransomSnapshot.events,mode:events.length?'live parse Ransomfeed':'snapshot Ransomfeed'};}
  async function loadRansomfeed(){try{return parseRansomfeedHtml(await getText('https://ransomfeed.it/'))}catch(e){return{...ransomSnapshot,mode:'snapshot: CORS o rete bloccata',error:e.message}}}
  function card(title,body){return`<article class="item global-item"><h3>${esc(title)}</h3>${body}</article>`}
  function renderRansomWatch(){let s=document.getElementById('ransom-watch');const hero=document.querySelector('.cti-hero');if(!hero)return;if(!s){s=document.createElement('section');s.id='ransom-watch';s.className='card global-card';hero.insertAdjacentElement('afterend',s);}const st=ransomData.stats,events=ransomData.events||[];s.innerHTML=`<div class="section-head"><div><span class="kicker">Ransomware Watch · dati Ransomfeed</span><h2>Ransomware Watch</h2><p class="muted">Dati OSINT pubblici da Ransomfeed. Se il browser blocca la lettura live, viene mostrato uno snapshot con data dichiarata.</p></div><div class="actions"><button id="refreshRansomBtn" class="btn primary" type="button">Aggiorna Ransomfeed</button><a class="btn ghost" target="_blank" rel="noreferrer" href="${ransomSource.url}">Apri fonte</a></div></div><section class="dashboard"><article class="metric"><small>7g globale</small><b>${st.global_7d??'-'}</b></article><article class="metric"><small>7g Italia</small><b>${st.italy_7d??'-'}</b></article><article class="metric"><small>Gruppi 2026</small><b>${st.groups_2026??'-'}</b></article><article class="metric"><small>Paesi 2026</small><b>${st.countries_2026??'-'}</b></article></section><div class="global-grid">${card('Ultimi eventi ransomware',`<ul>${events.slice(0,10).map(e=>`<li><b>${esc(e.date)} ${esc(e.country)}</b> · ${esc(e.victim)}<br><span class="muted">Gruppo: ${esc(e.group)} · ora: ${esc(e.time||'-')}</span></li>`).join('')}</ul>`)}${card('Fonte e limiti',`<p><b>Fonte:</b> <a class="pill" target="_blank" rel="noreferrer" href="${ransomSource.url}">${ransomSource.name}</a></p><p><b>Modalità:</b> ${esc(ransomData.mode||'snapshot')}</p><p><b>Licenza indicata:</b> ${esc(ransomSource.license)}</p><p class="muted">I dati indicano pubblicazioni OSINT su leak site o aggregatori. Non equivalgono da soli a prova forense, attribuzione certa o conferma dell’impatto.</p>`)}</div>`;const b=document.getElementById('refreshRansomBtn');if(b)b.onclick=refreshRansom;}
  async function refreshRansom(){const btn=document.getElementById('refreshRansomBtn');if(btn)btn.textContent='Aggiorno...';ransomData=await loadRansomfeed();localStorage.setItem('attack-profiler-ransomfeed',JSON.stringify(ransomData));renderRansomWatch();}
  function renderGlobal(){const box=$('globalFeed'),status=$('globalStatus');if(!box)return;const m=globalMoment||{landscape:staticLandscape(),kev:[],epss:[],errors:[]};const kev=(m.kev||[]).map(v=>`<li><b>${esc(v.id)}</b> · ${esc(v.vendor)} ${esc(v.product)}<br><span class="muted">${esc(v.title)} · scadenza CISA: ${esc(v.due)}</span></li>`).join('')||'<li>Feed non disponibile nel browser. Apri fonte ufficiale.</li>';const epss=(m.epss||[]).map(v=>`<li><b>${esc(v.id)}</b> · EPSS ${(v.epss*100).toFixed(1)}% · percentile ${(v.percentile*100).toFixed(1)}%</li>`).join('')||'<li>Feed non disponibile nel browser. Apri fonte ufficiale.</li>';const land=m.landscape||staticLandscape();box.innerHTML=card('Vulnerabilità sfruttate ora / recentemente',`<ul>${kev}</ul>`)+card('CVE con alta probabilità di exploit',`<ul>${epss}</ul>`)+card('Ransomfeed dati ransomware',`<p><b>7 giorni globale:</b> ${ransomData.stats.global_7d}</p><p><b>7 giorni Italia:</b> ${ransomData.stats.italy_7d}</p><p><b>Ultimi eventi:</b> ${(ransomData.events||[]).slice(0,3).map(e=>`${e.country} ${e.victim} (${e.group})`).join(' · ')}</p><p><a class="pill" target="_blank" rel="noreferrer" href="${ransomSource.url}">Apri Ransomfeed</a></p>`)+card('Aree e settori osservati',`<p><b>Settori più esposti:</b> ${land.sectors.map(esc).join(', ')}</p><p><b>Attori da considerare con cautela:</b> ${land.actors.map(esc).join(', ')}</p><p class="muted">${esc(land.note)}</p>`)+card('Fonti ufficiali e OSINT',officialLinks.map(x=>`<p><a class="pill" target="_blank" rel="noreferrer" href="${esc(x.url)}">${esc(x.name)}</a><br><span class="muted">${esc(x.use)}</span></p>`).join(''));if(status)status.textContent=`Aggiornato: ${safeDate(m.updated_at)} · modalità: ${m.mode||'fallback'}${m.errors&&m.errors.length?' · alcuni feed non disponibili via browser':''}`;renderMomentPanel();}
  async function refreshGlobal(){const status=$('globalStatus');if(status)status.textContent='Aggiornamento feed pubblici in corso...';const errors=[];let kev=[],epss=[];try{kev=await loadKev()}catch(e){errors.push('CISA KEV: '+e.message)}try{epss=await loadEpss()}catch(e){errors.push('FIRST EPSS: '+e.message)}ransomData=await loadRansomfeed();localStorage.setItem('attack-profiler-ransomfeed',JSON.stringify(ransomData));globalMoment={updated_at:new Date().toISOString(),mode:errors.length?'live parziale + fallback':'live feed pubblici',kev,epss,landscape:staticLandscape(),ransomware_watch:{source:ransomSource,items:ransomData.events,stats:ransomData.stats},errors};localStorage.setItem('attack-profiler-global-moment',JSON.stringify(globalMoment));renderRansomWatch();renderGlobal();}
  function renderMomentPanel(){const box=$('momentPanel');if(!box)return;const m=globalMoment||JSON.parse(localStorage.getItem('attack-profiler-global-moment')||'null')||{landscape:staticLandscape(),kev:[],epss:[],updated_at:new Date().toISOString(),mode:'fallback/strategico'};box.innerHTML=`<div class="item"><h3>Contesto globale da integrare nella valutazione</h3><p><b>Ransomfeed:</b> ${ransomData.stats.global_7d} eventi globali 7g · ${ransomData.stats.italy_7d} Italia 7g</p><p><b>Ultimi eventi:</b> ${(ransomData.events||[]).slice(0,4).map(e=>`${e.country} ${e.victim} (${e.group})`).join(' · ')}</p><p class="muted">Non è attribuzione automatica. Serve a orientare priorità, hunting e verifica di esposizione.</p></div>`;}
  const oldRenderTabs=renderTabs;renderTabs=function(){oldRenderTabs();const exists=[...document.querySelectorAll('.tab')].some(b=>b.dataset.tab==='moment');if(!exists){const b=document.createElement('button');b.className='btn ghost tab';b.dataset.tab='moment';b.textContent='Momento CTI';b.onclick=()=>showPanel('moment',b);$('tabs').insertBefore(b,document.querySelector('[data-tab="cti"]')||null);}}
  const oldRender=render;render=function(d){oldRender(d);renderMomentPanel();d.global_cti_moment={ransomfeed:{source:ransomSource.url,stats:ransomData.stats,events:(ransomData.events||[]).slice(0,10)}};$('report').textContent=$('report').textContent+`\n\nRansomware Watch\n- Fonte: ${ransomSource.name} · ${ransomSource.url}\n- 7g globale: ${ransomData.stats.global_7d}\n- 7g Italia: ${ransomData.stats.italy_7d}\n- Ultimi eventi: ${(ransomData.events||[]).slice(0,5).map(e=>`${e.date} ${e.country} ${e.victim} ${e.group}`).join(' | ')}\n- Limite: OSINT, non prova forense autonoma.`;}
  document.addEventListener('DOMContentLoaded',()=>{try{ransomData=JSON.parse(localStorage.getItem('attack-profiler-ransomfeed')||'null')||ransomSnapshot}catch(e){}renderRansomWatch();try{globalMoment=JSON.parse(localStorage.getItem('attack-profiler-global-moment')||'null')}catch(e){}renderGlobal();const btn=$('refreshGlobalBtn');if(btn)btn.onclick=refreshGlobal;});
  try{ransomData=JSON.parse(localStorage.getItem('attack-profiler-ransomfeed')||'null')||ransomSnapshot}catch(e){}renderRansomWatch();try{globalMoment=JSON.parse(localStorage.getItem('attack-profiler-global-moment')||'null')}catch(e){}renderGlobal();const btn=$('refreshGlobalBtn');if(btn)btn.onclick=refreshGlobal;
})();
