(function(){
  const officialLinks=[
    {name:'CISA Known Exploited Vulnerabilities',url:'https://www.cisa.gov/known-exploited-vulnerabilities-catalog',use:'Vulnerabilità sfruttate realmente, utile per priorità difensive.'},
    {name:'NVD/NIST CVE API',url:'https://nvd.nist.gov/developers/vulnerabilities',use:'CVE, CVSS, filtri KEV, date e keyword.'},
    {name:'FIRST EPSS',url:'https://www.first.org/epss/api',use:'Probabilità statistica di sfruttamento di una CVE.'},
    {name:'CERT-EU Security Advisories',url:'https://cert.europa.eu/publications/security-advisories',use:'Advisory europei aggiornati per organizzazioni UE.'},
    {name:'ENISA Threat Landscape',url:'https://www.enisa.europa.eu/publications/enisa-threat-landscape-2025',use:'Quadro strategico annuale su minacce, settori e tendenze.'}
  ];
  let globalMoment=null;
  function safeDate(d){try{return new Date(d).toLocaleDateString('it-IT')}catch(e){return String(d||'-')}}
  async function getJson(url){const r=await fetch(url,{cache:'no-store'});if(!r.ok)throw new Error('HTTP '+r.status);return r.json();}
  function staticLandscape(){return{updated_at:new Date().toISOString(),mode:'fallback/strategico',geo:[['Europa','Ransomware, DDoS, campagne contro PA, sanità, trasporti e servizi digitali.'],['Nord America','Ransomware, furto credenziali, compromissione servizi esposti, frodi BEC.'],['Asia-Pacifico','Sfruttamento vulnerabilità, supply chain, furto dati e attività cybercrime/espionage.'],['Medio Oriente','Hacktivism, DDoS, operazioni legate a tensioni geopolitiche.'],['Africa e America Latina','Frodi, ransomware opportunistico, compromissione account e servizi cloud.']],sectors:['PA/Gov','Sanità','Finanza','Energia/OT','Trasporti','Cloud/SaaS','PMI'],actors:['Ransomware ecosystem','Cybercrime finanziario','APT statali o para-statali','Hacktivism geopolitico','Insider/compromissione account'],note:'Quadro orientativo: usare solo come contesto, non come attribuzione automatica.'};}
  async function loadKev(){const data=await getJson('https://www.cisa.gov/sites/default/files/feeds/known_exploited_vulnerabilities.json');return(data.vulnerabilities||[]).slice(-8).reverse().map(v=>({id:v.cveID,title:v.vulnerabilityName||v.shortDescription||v.cveID,vendor:v.vendorProject||'-',product:v.product||'-',due:v.dueDate||'-',source:'CISA KEV'}));}
  async function loadEpss(){const data=await getJson('https://api.first.org/data/v1/epss?order=!epss&limit=8');return(data.data||[]).map(v=>({id:v.cve,epss:Number(v.epss||0),percentile:Number(v.percentile||0),source:'FIRST EPSS'}));}
  function card(title,body){return`<article class="item global-item"><h3>${esc(title)}</h3>${body}</article>`}
  function renderGlobal(){const box=$('globalFeed'),status=$('globalStatus');if(!box)return;const m=globalMoment||{landscape:staticLandscape(),kev:[],epss:[],errors:[]};const kev=(m.kev||[]).map(v=>`<li><b>${esc(v.id)}</b> · ${esc(v.vendor)} ${esc(v.product)}<br><span class="muted">${esc(v.title)} · scadenza CISA: ${esc(v.due)}</span></li>`).join('')||'<li>Feed non disponibile nel browser. Apri fonte ufficiale.</li>';const epss=(m.epss||[]).map(v=>`<li><b>${esc(v.id)}</b> · EPSS ${(v.epss*100).toFixed(1)}% · percentile ${(v.percentile*100).toFixed(1)}%</li>`).join('')||'<li>Feed non disponibile nel browser. Apri fonte ufficiale.</li>';const land=m.landscape||staticLandscape();box.innerHTML=card('Vulnerabilità sfruttate ora / recentemente',`<ul>${kev}</ul>`)+card('CVE con alta probabilità di exploit',`<ul>${epss}</ul>`)+card('Aree e settori osservati',`<div class="geo-list">${land.geo.map(([g,t])=>`<p><b>${esc(g)}</b><br>${esc(t)}</p>`).join('')}</div><p><b>Settori più esposti:</b> ${land.sectors.map(esc).join(', ')}</p><p><b>Attori probabili da considerare:</b> ${land.actors.map(esc).join(', ')}</p><p class="muted">${esc(land.note)}</p>`)+card('Fonti ufficiali',officialLinks.map(x=>`<p><a class="pill" target="_blank" rel="noreferrer" href="${esc(x.url)}">${esc(x.name)}</a><br><span class="muted">${esc(x.use)}</span></p>`).join(''));if(status)status.textContent=`Aggiornato: ${safeDate(m.updated_at)} · modalità: ${m.mode}${m.errors&&m.errors.length?' · alcuni feed non disponibili via browser':''}`;renderMomentPanel();}
  async function refreshGlobal(){const status=$('globalStatus');if(status)status.textContent='Aggiornamento feed pubblici in corso...';const errors=[];let kev=[],epss=[];try{kev=await loadKev()}catch(e){errors.push('CISA KEV: '+e.message)}try{epss=await loadEpss()}catch(e){errors.push('FIRST EPSS: '+e.message)}globalMoment={updated_at:new Date().toISOString(),mode:errors.length?'live parziale + fallback strategico':'live feed pubblici',kev,epss,landscape:staticLandscape(),errors};localStorage.setItem('attack-profiler-global-moment',JSON.stringify(globalMoment));renderGlobal();}
  function renderMomentPanel(){const box=$('momentPanel');if(!box)return;const m=globalMoment||JSON.parse(localStorage.getItem('attack-profiler-global-moment')||'null')||{landscape:staticLandscape(),kev:[],epss:[],updated_at:new Date().toISOString(),mode:'fallback/strategico'};const topKev=(m.kev||[]).slice(0,4).map(x=>`${x.id} (${x.vendor} ${x.product})`).join(', ')||'non disponibile';const topEpss=(m.epss||[]).slice(0,4).map(x=>`${x.id} EPSS ${(x.epss*100).toFixed(1)}%`).join(', ')||'non disponibile';box.innerHTML=`<div class="item"><h3>Contesto globale da integrare nella valutazione</h3><p><b>KEV recenti:</b> ${esc(topKev)}</p><p><b>EPSS alto:</b> ${esc(topEpss)}</p><p><b>Settori sensibili:</b> ${m.landscape.sectors.map(esc).join(', ')}</p><p><b>Attori da considerare con cautela:</b> ${m.landscape.actors.map(esc).join(', ')}</p><p class="muted">Non è attribuzione automatica. Serve a orientare priorità, hunting e verifica di esposizione.</p></div>`;}
  const oldRenderTabs=renderTabs;
  renderTabs=function(){oldRenderTabs();const exists=[...document.querySelectorAll('.tab')].some(b=>b.dataset.tab==='moment');if(!exists){const b=document.createElement('button');b.className='btn ghost tab';b.dataset.tab='moment';b.textContent='Momento CTI';b.onclick=()=>showPanel('moment',b);$('tabs').insertBefore(b,document.querySelector('[data-tab="cti"]')||null);}}
  const oldRender=render;
  render=function(d){oldRender(d);renderMomentPanel();if(globalMoment){d.global_cti_moment={updated_at:globalMoment.updated_at,mode:globalMoment.mode,kev:(globalMoment.kev||[]).slice(0,5),epss:(globalMoment.epss||[]).slice(0,5),landscape:globalMoment.landscape};$('report').textContent=makeReport(d)+`\n\nMomento CTI globale\n- Aggiornato: ${globalMoment.updated_at}\n- Modalità: ${globalMoment.mode}\n- KEV recenti: ${(globalMoment.kev||[]).slice(0,5).map(x=>x.id).join(', ')||'-'}\n- EPSS alto: ${(globalMoment.epss||[]).slice(0,5).map(x=>x.id).join(', ')||'-'}\n- Nota: quadro di contesto, non attribuzione certa.`;}}
  document.addEventListener('DOMContentLoaded',()=>{try{globalMoment=JSON.parse(localStorage.getItem('attack-profiler-global-moment')||'null')}catch(e){}renderGlobal();const btn=$('refreshGlobalBtn');if(btn)btn.onclick=refreshGlobal;});
  try{globalMoment=JSON.parse(localStorage.getItem('attack-profiler-global-moment')||'null')}catch(e){}
  renderGlobal();const btn=$('refreshGlobalBtn');if(btn)btn.onclick=refreshGlobal;
})();
