(function(){
  const $=id=>document.getElementById(id);
  const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const re={ip:/\b(?:\d{1,3}\.){3}\d{1,3}\b/g,url:/https?:\/\/[^\s"'<>]+/gi,hash:/\b[a-f0-9]{32,64}\b/gi,email:/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi,cve:/\bCVE-\d{4}-\d{4,}\b/gi};
  const keywords=[['ransomware',['encrypt','encrypted','ransom','shadow copy','vssadmin','lockbit','qilin','blackcat']],['phishing',['phish','credential','login failed','mfa','mailbox','forwarding','oauth']],['exfiltration',['upload','exfil','mega','dropbox','onedrive','archive','7z','rar','zip']],['lateral movement',['psexec','wmic','rdp','smb','admin$','remote logon']],['discovery',['whoami','net user','nltest','ipconfig','systeminfo','adfind']],['kev exploitation',['cve-','exploit','webshell','waf','http 500','path traversal']]];
  function inferStage(line){const l=line.toLowerCase();if(/phish|login|vpn|rdp|exploit|cve/.test(l))return'Accesso iniziale';if(/whoami|net user|nltest|ipconfig|systeminfo|adfind|discovery/.test(l))return'Discovery';if(/psexec|wmic|smb|admin\$|lateral/.test(l))return'Movimento laterale';if(/zip|7z|rar|archive|upload|exfil|mega|dropbox|onedrive/.test(l))return'Raccolta/Esfiltrazione';if(/encrypt|ransom|shadow|vssadmin|delete backup/.test(l))return'Impatto';return'Osservazione';}
  function findTimestamp(line){const m=line.match(/\b\d{4}-\d{2}-\d{2}[ T]\d{2}:\d{2}:\d{2}(?:\.\d+)?Z?\b|\b\d{2}\/\d{2}\/\d{4}[ T]\d{2}:\d{2}:\d{2}\b/);return m?m[0]:'';}
  function firstMatch(line,rx){const m=line.match(rx);return m?m[0]:'';}
  function parseLines(text){return String(text||'').split(/\r?\n/).map((line,i)=>line.trim()?{idx:i+1,raw:line.trim(),timestamp:findTimestamp(line),src_ip:firstMatch(line,re.ip),user:firstMatch(line,re.email)||((line.match(/user(?:name)?[=: ]+([\w.\\-]+)/i)||[])[1]||''),host:((line.match(/host(?:name)?[=: ]+([\w.-]+)/i)||[])[1]||''),stage:inferStage(line),severity:/error|fail|denied|ransom|encrypt|critical|alert/i.test(line)?'alta':/warn|suspicious|anomal/i.test(line)?'media':'bassa'}:null).filter(Boolean).slice(0,500);}
  function extractAll(text){const out=[];for(const [type,rx] of Object.entries(re)){const ms=String(text||'').match(rx)||[];[...new Set(ms.map(x=>x.replace(/[),.;]+$/,'')))].slice(0,40).forEach(v=>out.push({type,value:v}));}return out;}
  function correlate(events,iocs){const map={};events.forEach(e=>{[e.user,e.host,e.src_ip].filter(Boolean).forEach(k=>{map[k]=map[k]||{key:k,count:0,stages:new Set(),severity:'bassa'};map[k].count++;map[k].stages.add(e.stage);if(e.severity==='alta')map[k].severity='alta';else if(e.severity==='media'&&map[k].severity!=='alta')map[k].severity='media';});});return Object.values(map).sort((a,b)=>b.count-a.count).slice(0,12).map(x=>({...x,stages:[...x.stages]}));}
  function suggestPlaybooks(text){const l=String(text||'').toLowerCase();return keywords.filter(([,ks])=>ks.some(k=>l.includes(k))).map(([name])=>name);}
  function decision(conf,impact){if(conf>=70&&impact==='alto')return'Escalation e contenimento consigliati';if(conf>=70)return'Validare e applicare mitigazione mirata';if(impact==='alto')return'Validazione urgente e hunting mirato';return'Monitoraggio e contestualizzazione';}
  function renderOperational(){const input=$('input');const text=input?input.value:'';const box=$('operationalPanel');if(!box)return;const events=parseLines(text),iocs=extractAll(text),corr=correlate(events,iocs),plays=suggestPlaybooks(text);const impact=/domain controller|server critico|sanità|pa |ot\/ics|backup|ransom|encrypt|exfil/i.test(text)?'alto':/server|cloud|finance|vpn/i.test(text)?'medio':'basso';const conf=Math.min(95,30+Math.min(events.length,20)*2+Math.min(iocs.length,10)*3+(corr.length?10:0));box.innerHTML=`<h2>Analisi operativa locale</h2><p class="muted">Parser locale: non invia log o file a servizi esterni. Estrae timeline, evidenze e correlazioni dal testo caricato/incollato.</p><section class="dashboard"><article class="metric"><small>Eventi</small><b>${events.length}</b></article><article class="metric"><small>IOC</small><b>${iocs.length}</b></article><article class="metric"><small>Confidence</small><b>${conf}%</b></article><article class="metric"><small>Decisione</small><b>${esc(decision(conf,impact))}</b></article></section><div class="global-grid"><article class="item"><h3>Timeline</h3><ul>${events.slice(0,12).map(e=>`<li><b>${esc(e.timestamp||'#'+e.idx)}</b> · ${esc(e.stage)} · <span class="muted">${esc(e.raw.slice(0,140))}</span></li>`).join('')||'<li>Nessun evento strutturato rilevato.</li>'}</ul></article><article class="item"><h3>Correlazioni</h3><ul>${corr.map(c=>`<li><b>${esc(c.key)}</b> · ${c.count} eventi · ${esc(c.stages.join(', '))} · severità ${esc(c.severity)}</li>`).join('')||'<li>Nessuna correlazione forte.</li>'}</ul></article><article class="item"><h3>IOC estratti</h3><ul>${iocs.slice(0,15).map(i=>`<li><b>${esc(i.type)}</b> · ${esc(i.value)}</li>`).join('')||'<li>Nessun IOC rilevato.</li>'}</ul></article><article class="item"><h3>Playbook suggeriti</h3><p>${plays.length?plays.map(esc).join(', '):'Nessun playbook specifico. Valutare manualmente.'}</p><p><a class="pill" href="playbooks.html">Apri playbook</a></p></article></div><p class="privacy"><b>Fatti vs inferenze:</b> timeline e IOC sono estratti dal testo; fasi, confidence e playbook sono inferenze locali da validare.</p>`;try{localStorage.setItem('attack-profiler-operational',JSON.stringify({events,iocs,corr,plays,conf,impact,updated_at:new Date().toISOString()}));}catch(e){}}
  document.addEventListener('DOMContentLoaded',()=>{const target=document.getElementById('analisi');if(target&&!document.getElementById('operationalPanel')){const s=document.createElement('section');s.id='operationalPanel';s.className='card';target.insertAdjacentElement('afterend',s);}const input=$('input');if(input){input.addEventListener('input',()=>setTimeout(renderOperational,80));}const files=$('logFiles');if(files){files.addEventListener('change',()=>setTimeout(renderOperational,250));}renderOperational();});
})();
