const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const ransomSource={name:'Ransomfeed',url:'https://ransomfeed.it/',kind:'OSINT pubblico ransomware',license:'CC BY 4.0'};
const ransomSnapshot={updated_at:'2026-07-05 snapshot da pagina pubblica',mode:'snapshot Ransomfeed',stats:{global_7d:192,italy_7d:5,groups_2026:104,countries_2026:123,global_total:26808,global_2026:4641,italy_total:781,italy_2026:143},events:[{date:'2026-07-03',country:'USA',victim:'oakparkmi.gov',group:'incransom',time:'00:55'},{date:'2026-07-03',country:'Switzerland',victim:'Ferrum AG',group:'anubis',time:'00:51'},{date:'2026-07-02',country:'Spain',victim:'holidaypalace.com',group:'apt73/bashe',time:'17:57'},{date:'2026-07-02',country:'Italy',victim:'flazio.com',group:'apt73/bashe',time:'16:21'}]};
const controls=['MFA attiva sugli account critici','EDR o antivirus gestito sugli endpoint','Log centralizzati in SIEM','Backup offline o immutabili testati','Patch management definito','Privilegi minimi e account admin separati','SPF, DKIM, DMARC e sandbox email','Segmentazione di rete e controllo egress','Audit log cloud con retention','Playbook incident response'];
const glossary=[['CTI','Cyber Threat Intelligence: trasformare dati grezzi in decisioni difensive.'],['IOC','Indicatore puntuale: IP, dominio, URL, hash, email.'],['IOA','Indicatore di comportamento: utile anche se gli IOC cambiano.'],['TTP','Tattiche, tecniche e procedure osservate.'],['MITRE ATT&CK','Knowledge base per classificare comportamenti avversari.'],['Confidence','Quanto è solido il collegamento tra evidenza e decisione.'],['Ransomware Watch','Lettura OSINT di vittime e gruppi pubblicati, non prova forense autonoma.'],['KEV','Catalogo CISA di vulnerabilità note come sfruttate.'],['EPSS','Probabilità statistica di exploitation di una CVE.'],['SIEM','Piattaforma di raccolta e correlazione log.'],['EDR','Telemetria e risposta su endpoint.']];
function loadScript(src){if(document.querySelector(`script[src="${src}"]`))return;const s=document.createElement('script');s.src=src;s.defer=true;document.head.appendChild(s);}
function initCommon(){const t=$('themeBtn');if(t)t.onclick=()=>document.body.classList.toggle('light');if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{});loadScript('chatbot.js');}
function kpi(label,value){return`<article class="metric"><small>${esc(label)}</small><b>${esc(value)}</b></article>`}
function renderRansom(data=ransomSnapshot){const k=$('ransomKpis'),e=$('ransomEvents'),m=$('ransomMeta');if(k){k.innerHTML=kpi('7g globale',data.stats.global_7d)+kpi('7g Italia',data.stats.italy_7d)+kpi('Gruppi 2026',data.stats.groups_2026)+kpi('Paesi 2026',data.stats.countries_2026)}if(e){e.innerHTML=`<div class="global-grid">${data.events.map(x=>`<article class="item"><h3>${esc(x.country)} · ${esc(x.victim)}</h3><p><b>Gruppo:</b> ${esc(x.group)}</p><p><b>Data:</b> ${esc(x.date)} ${esc(x.time||'')}</p><p><b>Fonte:</b> <a class="pill" target="_blank" rel="noreferrer" href="${ransomSource.url}">${ransomSource.name}</a></p></article>`).join('')}</div>`}if(m)m.textContent=`Modalità: ${data.mode||'snapshot'} · aggiornamento: ${data.updated_at||'-'} · uso: OSINT di contesto, non prova forense.`;}
async function refreshRansom(){const b=$('refreshRansomBtn');if(b)b.textContent='Aggiorno...';let data=ransomSnapshot;try{const r=await fetch(ransomSource.url,{cache:'no-store'});const html=await r.text();const text=html.replace(/<[^>]+>/g,' ').replace(/\s+/g,' ');data={...ransomSnapshot,updated_at:new Date().toISOString(),mode:'lettura live pagina pubblica'};const n=re=>{const m=text.match(re);return m?Number(m[1]):null};data.stats.global_7d=n(/7 giorni globale\s+(\d+)/i)||data.stats.global_7d;data.stats.italy_7d=n(/7 giorni Italia\s+(\d+)/i)||data.stats.italy_7d;data.stats.groups_2026=n(/Gruppi attivi 2026\s+(\d+)/i)||data.stats.groups_2026;data.stats.countries_2026=n(/Paesi colpiti 2026\s+(\d+)/i)||data.stats.countries_2026;}catch(e){data={...ransomSnapshot,mode:'snapshot: lettura live non disponibile nel browser'}}localStorage.setItem('attack-profiler-ransomfeed',JSON.stringify(data));renderRansom(data);if(b)b.textContent='Aggiorna Ransomfeed';}
function renderSecurity(){const box=$('securityChecklist');if(!box)return;box.innerHTML=controls.map((c,i)=>`<label class="check-item"><input type="checkbox" data-sec="${i}"><span>${esc(c)}</span></label>`).join('');box.querySelectorAll('input').forEach(x=>x.onchange=updateSecurity);updateSecurity();}
function updateSecurity(){const checked=document.querySelectorAll('[data-sec]:checked').length,total=controls.length,p=Math.round(checked/total*100);const bar=$('securityScore'),txt=$('securityText');if(bar)bar.style.width=p+'%';if(txt)txt.textContent=`Controlli presenti: ${checked}/${total} · ${p}% · ${p>=80?'buona maturità difensiva':p>=50?'maturità intermedia':'postura fragile'}.`;}
function renderGlossary(){const box=$('glossary'),q=($('glossarySearch')?.value||'').toLowerCase();if(!box)return;box.innerHTML=glossary.filter(([a,b])=>(a+' '+b).toLowerCase().includes(q)).map(([a,b])=>`<article class="item"><h3>${esc(a)}</h3><p>${esc(b)}</p></article>`).join('');const s=$('glossarySearch');if(s&&!s.dataset.ready){s.dataset.ready=1;s.oninput=renderGlossary;}}
document.addEventListener('DOMContentLoaded',()=>{initCommon();renderRansom(JSON.parse(localStorage.getItem('attack-profiler-ransomfeed')||'null')||ransomSnapshot);renderSecurity();renderGlossary();const b=$('refreshRansomBtn');if(b)b.onclick=refreshRansom;});
