(function(){
  const controls=[
    ['mfa','MFA attiva sugli account critici'],['edr','EDR o antivirus gestito sugli endpoint'],['siem','Log centralizzati in SIEM o piattaforma equivalente'],['backup','Backup offline o immutabili testati'],['patch','Processo di patch management definito'],['least','Privilegi minimi e account admin separati'],['email','Protezione email con SPF, DKIM, DMARC e sandbox'],['network','Segmentazione di rete e controllo egress'],['cloud','Audit log cloud e retention adeguata'],['ir','Playbook di incident response e contatti di escalation']
  ];
  function initChecklist(){const box=$('securityChecklist');if(!box)return;box.innerHTML=controls.map(([id,label])=>`<label class="check-item"><input type="checkbox" data-sec="${id}"><span>${esc(label)}</span></label>`).join('');box.querySelectorAll('input').forEach(x=>x.onchange=updateScore);updateScore();}
  function updateScore(){const total=controls.length,checked=document.querySelectorAll('[data-sec]:checked').length,p=Math.round((checked/total)*100);const bar=$('securityScore'),txt=$('securityText');if(bar)bar.style.width=p+'%';if(txt){const level=p>=80?'buona maturità difensiva':p>=50?'maturità intermedia, rafforzare i controlli mancanti':'postura fragile, priorità a log, MFA, backup e risposta incidenti';txt.textContent=`Controlli presenti: ${checked}/${total} · ${p}% · ${level}.`;}}
  async function readFile(file){const max=2*1024*1024;if(file.size>max)return`\n\n[FILE: ${file.name}]\nFile troppo grande per anteprima locale rapida (${Math.round(file.size/1024)} KB). Inserire un estratto testuale rilevante.\n`;try{const text=await file.text();return`\n\n[FILE: ${file.name} · ${Math.round(file.size/1024)} KB]\n${text.slice(0,12000)}${text.length>12000?'\n[estratto limitato a 12000 caratteri]':''}\n`;}catch(e){return`\n\n[FILE: ${file.name}]\nImpossibile leggere il file come testo. Esporta il log in TXT, CSV, JSON o XML.\n`;}}
  async function handleFiles(e){const files=[...e.target.files||[]],preview=$('filePreview');if(!files.length)return;let added='',names=[];for(const f of files){names.push(`${f.name} (${Math.round(f.size/1024)} KB)`);added+=await readFile(f);}const current=$('input').value.trim();$('input').value=(current?current+'\n':'')+'=== ESTRATTI FILE CARICATI LOCALMENTE ==='+added;preview.textContent='Caricati localmente: '+names.join(', ');$('status').textContent='File letti localmente nel browser. Controlla il testo prima di avviare l’analisi.';}
  const oldRender=render;
  render=function(d){oldRender(d);const checks=[...document.querySelectorAll('[data-sec]:checked')].map(x=>x.parentElement.textContent.trim());if(checks.length){d.security_posture={checked_controls:checks,score:Math.round((checks.length/controls.length)*100)};$('report').textContent=makeReport(d)+`\n\nVerifica sicurezza informatica\n- Score controlli: ${d.security_posture.score}%\n${checks.map(x=>'- '+x).join('\n')}`;}}
  document.addEventListener('DOMContentLoaded',()=>{initChecklist();const f=$('logFiles');if(f)f.onchange=handleFiles;});
  initChecklist();const f=$('logFiles');if(f)f.onchange=handleFiles;
})();
